### PR TITLE
Set minimal title length from 4 to 2

### PR DESCRIPTION
**Pull request by asaunier**
In many cases it would be useful to be able to use 2 or 3-characters document titles.
For instance "Uja": http://www.camptocamp.org/summits/41269/fr/uja (a "." has been added to reach the current 4-character limit).

Route names minimum size is already set to 2:
https://github.com/c2corg/camptocamp.org/blob/master/apps/frontend/modules/routes/validate/edit.yml#L41-L42

Please note that the error message (already used for routes) is not translated and not even available in http://c2ci18n.appspot.com/
``this name is too short (2 characters minimum)``

### CODE REVIEW

**Comment by asaunier** [comment]
Any comments or objections?
If none I will merge the PR those days.

**Comment by gottferdom** [comment]
Seems fine to me. Have you been able to add new translation items on c2ci18n?

**Comment by fbunoz** [comment]
J'ai ajouté le msgid, il suffit de mettre à jour l'i18n avec le script qui
va bien.

2016-01-04 22:34 GMT+01:00 Bruno Besson <notifications@github.com>:

**Comment by asaunier** [comment]
> Seems fine to me.

Thanks! I will merge tonight after running the i18n script.

> J'ai ajouté le msgid, il suffit de mettre à jour l'i18n avec le script qui va bien.

Super, merci Bubu !

**Comment by asaunier** [comment]
The translations (including some from the xreports module) have been updated at 8084d42
Merging the PR.

**Pull request merged**
